# Generated by Django 2.2.6 on 2019-11-03 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 19, 9, 16, 451838, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
